/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package appexpreg3;

import java.util.Random;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

/**
 *
 * @author DEVELOP17
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        this.labelError.setVisible(false);
        this.labelCorrecto.setVisible(false);
        this.labelError1.setVisible(false);
        this.labelCorrecto1.setVisible(false);
        this.labelError2.setVisible(false);
        this.labelCorrecto2.setVisible(false);
        this.labelError3.setVisible(false);
        this.labelCorrecto3.setVisible(false);
        this.labelError4.setVisible(false);
        this.labelCorrecto4.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        textNumero1 = new javax.swing.JTextField();
        btnAleatorio1 = new javax.swing.JButton();
        btnValidar1 = new javax.swing.JButton();
        labelError = new javax.swing.JLabel();
        labelCorrecto = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextPane2 = new javax.swing.JTextPane();
        jPanel7 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        textNumero2 = new javax.swing.JTextField();
        btnAleatorio2 = new javax.swing.JButton();
        btnValidar2 = new javax.swing.JButton();
        labelError1 = new javax.swing.JLabel();
        labelCorrecto1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTextPane5 = new javax.swing.JTextPane();
        jPanel8 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        textNumero3 = new javax.swing.JTextField();
        btnAleatorio3 = new javax.swing.JButton();
        btnValidar3 = new javax.swing.JButton();
        labelError2 = new javax.swing.JLabel();
        labelCorrecto2 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextPane4 = new javax.swing.JTextPane();
        jPanel9 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        textNumero4 = new javax.swing.JTextField();
        btnAleatorio4 = new javax.swing.JButton();
        btnValidar4 = new javax.swing.JButton();
        labelError3 = new javax.swing.JLabel();
        labelCorrecto3 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextPane3 = new javax.swing.JTextPane();
        jPanel10 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        textNumero5 = new javax.swing.JTextField();
        btnAleatorio5 = new javax.swing.JButton();
        btnValidar5 = new javax.swing.JButton();
        labelError4 = new javax.swing.JLabel();
        labelCorrecto4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTabbedPane1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jTabbedPane1StateChanged(evt);
            }
        });

        jLabel1.setText("Número");

        btnAleatorio1.setText("Aleatorio");
        btnAleatorio1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAleatorio1ActionPerformed(evt);
            }
        });

        btnValidar1.setText("Validar");
        btnValidar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnValidar1ActionPerformed(evt);
            }
        });

        labelError.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelError.setForeground(new java.awt.Color(255, 0, 51));
        labelError.setText("No es válidooo");

        labelCorrecto.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelCorrecto.setForeground(new java.awt.Color(0, 204, 0));
        labelCorrecto.setText("Es Valido");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(textNumero1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(btnAleatorio1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addComponent(btnValidar1)
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(labelError)
                .addGap(18, 18, 18)
                .addComponent(labelCorrecto, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(textNumero1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAleatorio1)
                    .addComponent(btnValidar1))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelError)
                    .addComponent(labelCorrecto))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jScrollPane2.setEnabled(false);

        jTextPane1.setEditable(false);
        jTextPane1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTextPane1.setText("1.- ESCRIBA UNA EXPRESION REGULAR PARA  VALIDAR NUMEROS ENTEROS.");
        jScrollPane2.setViewportView(jTextPane1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 465, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(79, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Preg. 1", jPanel1);

        jScrollPane3.setEnabled(false);

        jTextPane2.setEditable(false);
        jTextPane2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTextPane2.setText("2.- ESCRIBA UNA EXPRESION REGULAR PARA VALIDAR NUMEROS ENTEROS NEGATIVOS");
        jScrollPane3.setViewportView(jTextPane2);

        jLabel2.setText("Número");

        btnAleatorio2.setText("Aleatorio");
        btnAleatorio2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAleatorio2ActionPerformed(evt);
            }
        });

        btnValidar2.setText("Validar");
        btnValidar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnValidar2ActionPerformed(evt);
            }
        });

        labelError1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelError1.setForeground(new java.awt.Color(255, 0, 51));
        labelError1.setText("No es válidooo");

        labelCorrecto1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelCorrecto1.setForeground(new java.awt.Color(0, 204, 0));
        labelCorrecto1.setText("Es Valido");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(textNumero2, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(btnAleatorio2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addComponent(btnValidar2)
                .addContainerGap())
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(labelError1)
                .addGap(18, 18, 18)
                .addComponent(labelCorrecto1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(textNumero2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAleatorio2)
                    .addComponent(btnValidar2))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelError1)
                    .addComponent(labelCorrecto1))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 465, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(112, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Preg. 2", jPanel3);

        jScrollPane6.setEnabled(false);

        jTextPane5.setEditable(false);
        jTextPane5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTextPane5.setText("3.- ESCRIBA UNA EXPRESION REGULAR PARA VALIDAR UN NUMERO DE CONTROL DEL TEC. LAGUNA (NO IMPORTA LA SECUENCIA, SOLO LA CANTIDAD) ");
        jScrollPane6.setViewportView(jTextPane5);

        jLabel3.setText("Número");

        btnAleatorio3.setText("Aleatorio");
        btnAleatorio3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAleatorio3ActionPerformed(evt);
            }
        });

        btnValidar3.setText("Validar");
        btnValidar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnValidar3ActionPerformed(evt);
            }
        });

        labelError2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelError2.setForeground(new java.awt.Color(255, 0, 51));
        labelError2.setText("No es válidooo");

        labelCorrecto2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelCorrecto2.setForeground(new java.awt.Color(0, 204, 0));
        labelCorrecto2.setText("Es Valido");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(textNumero3, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(btnAleatorio3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addComponent(btnValidar3)
                .addContainerGap())
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(labelError2)
                .addGap(18, 18, 18)
                .addComponent(labelCorrecto2, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(textNumero3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAleatorio3)
                    .addComponent(btnValidar3))
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelError2)
                    .addComponent(labelCorrecto2))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 465, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Preg. 3", jPanel4);

        jScrollPane5.setEnabled(false);

        jTextPane4.setEditable(false);
        jTextPane4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTextPane4.setText("4.- ESCRIBA UNA EXPRESION REGULAR PARA VALIDAR NUMEROS DE CONTROL DEL TEC LAGUNA PARA LOS ESTUDIANTES QUE INGRESARON EN EL AÑO 2020 ");
        jScrollPane5.setViewportView(jTextPane4);

        jLabel4.setText("Número");

        btnAleatorio4.setText("Aleatorio");
        btnAleatorio4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAleatorio4ActionPerformed(evt);
            }
        });

        btnValidar4.setText("Validar");
        btnValidar4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnValidar4ActionPerformed(evt);
            }
        });

        labelError3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelError3.setForeground(new java.awt.Color(255, 0, 51));
        labelError3.setText("No es válidooo");

        labelCorrecto3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelCorrecto3.setForeground(new java.awt.Color(0, 204, 0));
        labelCorrecto3.setText("Es Valido");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(textNumero4, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(btnAleatorio4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addComponent(btnValidar4)
                .addContainerGap())
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(labelError3)
                .addGap(18, 18, 18)
                .addComponent(labelCorrecto3, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(textNumero4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAleatorio4)
                    .addComponent(btnValidar4))
                .addGap(18, 18, 18)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelError3)
                    .addComponent(labelCorrecto3))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 465, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68))
        );

        jTabbedPane1.addTab("Preg. 4", jPanel5);

        jScrollPane4.setEnabled(false);

        jTextPane3.setEditable(false);
        jTextPane3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTextPane3.setText("5.- ESCRIBA UNA EXPRESION REGULAR PARA VALIDAR IDENTIFICADORES DE PRODUCTOS QUE CONTENGAN 4 DIGITOS + 2 LETRAS + 2 DIGITOS");
        jScrollPane4.setViewportView(jTextPane3);

        jLabel5.setText("Número");

        btnAleatorio5.setText("Aleatorio");
        btnAleatorio5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAleatorio5ActionPerformed(evt);
            }
        });

        btnValidar5.setText("Validar");
        btnValidar5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnValidar5ActionPerformed(evt);
            }
        });

        labelError4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelError4.setForeground(new java.awt.Color(255, 0, 51));
        labelError4.setText("No es válidooo");

        labelCorrecto4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelCorrecto4.setForeground(new java.awt.Color(0, 204, 0));
        labelCorrecto4.setText("Es Valido");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(textNumero5, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(btnAleatorio5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addComponent(btnValidar5)
                .addContainerGap())
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(labelError4)
                .addGap(18, 18, 18)
                .addComponent(labelCorrecto4, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(textNumero5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAleatorio5)
                    .addComponent(btnValidar5))
                .addGap(18, 18, 18)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelError4)
                    .addComponent(labelCorrecto4))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 465, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(64, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Preg. 5", jPanel6);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnValidar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnValidar1ActionPerformed
        String nc = this.textNumero1.getText();
        String regExp = "([0-9])\\d";
        Pattern pStr = Pattern.compile(regExp);
        Matcher mStr = pStr.matcher(nc);
        if (mStr.matches()) {
            this.labelError.setVisible(false);
            this.labelCorrecto.setVisible(true);
        } else {
            this.labelError.setVisible(true);
            this.labelCorrecto.setVisible(false);
        }
    }//GEN-LAST:event_btnValidar1ActionPerformed

    private void btnAleatorio1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAleatorio1ActionPerformed
        int valorEntero = (int) Math.floor(Math.random() * (0 - 100 + 1) + 100);
        this.textNumero1.setText(valorEntero + "");
    }//GEN-LAST:event_btnAleatorio1ActionPerformed

    private void jTabbedPane1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jTabbedPane1StateChanged
        this.labelError.setVisible(false);
        this.labelCorrecto.setVisible(false);
        this.labelError1.setVisible(false);
        this.labelCorrecto1.setVisible(false);
        this.labelError2.setVisible(false);
        this.labelCorrecto2.setVisible(false);
        this.labelError3.setVisible(false);
        this.labelCorrecto3.setVisible(false);
        this.labelError4.setVisible(false);
        this.labelCorrecto4.setVisible(false);
    }//GEN-LAST:event_jTabbedPane1StateChanged

    private void btnAleatorio2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAleatorio2ActionPerformed
        int valorEntero = (int) Math.floor(Math.random() * (100 - 0 + 1) - 100);
        this.textNumero2.setText(valorEntero + "");
    }//GEN-LAST:event_btnAleatorio2ActionPerformed

    private void btnValidar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnValidar2ActionPerformed
        String nc = this.textNumero2.getText();
        String regExp = "(-[0-9])\\d";
        Pattern pStr = Pattern.compile(regExp);
        Matcher mStr = pStr.matcher(nc);
        if (mStr.matches()) {
            this.labelError1.setVisible(false);
            this.labelCorrecto1.setVisible(true);
        } else {
            this.labelError1.setVisible(true);
            this.labelCorrecto1.setVisible(false);
        }
    }//GEN-LAST:event_btnValidar2ActionPerformed

    private void btnAleatorio3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAleatorio3ActionPerformed
        int valorEntero = (int) Math.floor(Math.random() * (10000000 - 100000000 + 1) + 100000000);
        this.textNumero3.setText(valorEntero + "");
    }//GEN-LAST:event_btnAleatorio3ActionPerformed

    private void btnValidar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnValidar3ActionPerformed
        String nc = this.textNumero3.getText();
        String regExp = "([0-9]){8}";
        Pattern pStr = Pattern.compile(regExp);
        Matcher mStr = pStr.matcher(nc);
        if (mStr.matches()) {
            this.labelError2.setVisible(false);
            this.labelCorrecto2.setVisible(true);
        } else {
            this.labelError2.setVisible(true);
            this.labelCorrecto2.setVisible(false);
        }
    }//GEN-LAST:event_btnValidar3ActionPerformed

    private void btnAleatorio4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAleatorio4ActionPerformed
        int con = (int) Math.floor(Math.random() * (0 - 10 + 1) + 10);
        int par1, par2;
        if (con == 5) {
            par1 = 20;
            par2 = 13;
        } else {
            par1 = (int) Math.floor(Math.random() * (10 - 20 + 1) + 20);
            par2 = (int) Math.floor(Math.random() * (10 - 15 + 1) + 15);
        }

        int par3y4 = (int) Math.floor(Math.random() * (1000 - 10000 + 1) + 10000);

        this.textNumero4.setText(par1 + "" + par2 + "" + par3y4);
    }//GEN-LAST:event_btnAleatorio4ActionPerformed

    private void btnValidar4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnValidar4ActionPerformed
        String nc = this.textNumero4.getText();
        String regExp = "2013([0-9]){4}";
        Pattern pStr = Pattern.compile(regExp);
        Matcher mStr = pStr.matcher(nc);
        if (mStr.matches()) {
            this.labelError3.setVisible(false);
            this.labelCorrecto3.setVisible(true);
        } else {
            this.labelError3.setVisible(true);
            this.labelCorrecto3.setVisible(false);
        }
    }//GEN-LAST:event_btnValidar4ActionPerformed

    private void btnAleatorio5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAleatorio5ActionPerformed
        int con = (int) Math.floor(Math.random() * (0 - 10 + 1) + 10);
        int par1, par3;
        String par2;
        if (con <= 5) {
            par1 = (int) Math.floor(Math.random() * (1000 - 10000 + 1) + 10000);
            par3 = (int) Math.floor(Math.random() * (10 - 20 + 1) + 20);
            par2 = getCadena(2);
        } else {
            par1 = (int) Math.floor(Math.random() * (10 - 10000 + 1) + 10000);
            par2 = getCadena((int) Math.floor(Math.random() * (0 - 3 + 1) + 3));
            par3 = (int) Math.floor(Math.random() * (10 - 15 + 1) + 15);
        }

        this.textNumero5.setText(par1 + "" + par2 + "" + par3);
    }//GEN-LAST:event_btnAleatorio5ActionPerformed

    String getCadena(int con) {
        // Los caracteres de interés en un array de char.
        char[] chars = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ".toCharArray();

        // Longitud del array de char.
        int charsLength = chars.length;

        // Instanciamos la clase Random
        Random random = new Random();

        // Un StringBuffer para componer la cadena aleatoria de forma eficiente
        StringBuffer buffer = new StringBuffer();

        // Bucle para elegir una cadena de 10 caracteres al azar
        for (int i = 0; i < con; i++) {
            // Añadimos al buffer un caracter al azar del array
            char r = chars[random.nextInt(charsLength)];
            buffer.append(r);
        }

        // Y solo nos queda hacer algo con la cadena
        return buffer.toString();
    }

    private void btnValidar5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnValidar5ActionPerformed
        String nc = this.textNumero5.getText();
        String regExp = "(\\d){4}([A-Za-z]){2}(\\d){2}";
        Pattern pStr = Pattern.compile(regExp);
        Matcher mStr = pStr.matcher(nc);
        if (mStr.matches()) {
            this.labelError4.setVisible(false);
            this.labelCorrecto4.setVisible(true);
        } else {
            this.labelError4.setVisible(true);
            this.labelCorrecto4.setVisible(false);
        }
    }//GEN-LAST:event_btnValidar5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAleatorio1;
    private javax.swing.JButton btnAleatorio2;
    private javax.swing.JButton btnAleatorio3;
    private javax.swing.JButton btnAleatorio4;
    private javax.swing.JButton btnAleatorio5;
    private javax.swing.JButton btnValidar1;
    private javax.swing.JButton btnValidar2;
    private javax.swing.JButton btnValidar3;
    private javax.swing.JButton btnValidar4;
    private javax.swing.JButton btnValidar5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JTextPane jTextPane2;
    private javax.swing.JTextPane jTextPane3;
    private javax.swing.JTextPane jTextPane4;
    private javax.swing.JTextPane jTextPane5;
    private javax.swing.JLabel labelCorrecto;
    private javax.swing.JLabel labelCorrecto1;
    private javax.swing.JLabel labelCorrecto2;
    private javax.swing.JLabel labelCorrecto3;
    private javax.swing.JLabel labelCorrecto4;
    private javax.swing.JLabel labelError;
    private javax.swing.JLabel labelError1;
    private javax.swing.JLabel labelError2;
    private javax.swing.JLabel labelError3;
    private javax.swing.JLabel labelError4;
    private javax.swing.JTextField textNumero1;
    private javax.swing.JTextField textNumero2;
    private javax.swing.JTextField textNumero3;
    private javax.swing.JTextField textNumero4;
    private javax.swing.JTextField textNumero5;
    // End of variables declaration//GEN-END:variables
}
